# Funciones principales de Numpy

In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)
arr

array([ 3,  9,  2,  5,  6,  7,  6,  1, 11,  5])

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[ 3,  9,  2,  5,  6],
       [ 7,  6,  1, 11,  5]])

# .max() & .argmax()

Devolver el valor mayor y su indice.

In [6]:
arr.max() # Devuelve el numero mayor del array

11

In [9]:
matriz.max(1) # (Eje)
# 1 Filas. 
# 0 Columnas. 

array([ 9, 11])

In [10]:
arr.argmax() # Devuelve el lugar del array mayor. 

8

In [11]:
matriz.argmax(1)

array([1, 3])

# .min() & .argmin()
Devolver el valor mas pequeño y su indice. 

In [12]:

arr.min()

1

In [13]:
matriz.min()

1

In [14]:
arr.argmin()

7

In [19]:
matriz.argmin(1)

array([2, 2])

# Estadística Básica.    
## .ptp()
Diferencia que hay entre el minimo y el maximo numero.  *(Rango)*

In [20]:
arr

array([ 3,  9,  2,  5,  6,  7,  6,  1, 11,  5])

In [22]:
arr.ptp()

10

In [31]:
matriz

array([[ 1,  2,  3,  5,  5],
       [ 6,  6,  7,  9, 11]])

In [32]:
matriz.ptp(1)

array([4, 5])

## .sort()
Acomodar los datos de menor a mayor. 

In [24]:
arr.sort()
arr

array([ 1,  2,  3,  5,  5,  6,  6,  7,  9, 11])

In [37]:
matriz.sort(0)
matriz

array([[ 1,  2,  3,  5,  5],
       [ 6,  6,  7,  9, 11]])

## .percentile()
permite generar el percentile que ocupemos. 

In [38]:
np.percentile(arr,50) #(array, percentile a obtener)

5.5

In [39]:
np.percentile(matriz,50,1)

array([3., 7.])

## .median()

Regresa la mediana de los datos.

In [40]:
np.median(arr)
np.median(matriz,1)

array([3., 7.])

## .std() & .var()

STD ->  Obtener la desviación estándar de los datos. 
VAR ->  Obtener la varianza de los datos.

In [41]:
np.std(arr)

2.9068883707497264

In [43]:
np.std(matriz,0)

array([2.5, 2. , 2. , 2. , 3. ])

In [44]:
np.var(arr)

8.45

In [45]:
np.var(matriz)

8.45

## .mean()

Media de los datos o promedio

In [46]:
np.mean(matriz,1)

array([3.2, 7.8])

# .concatenate()

Concatenar arrays

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [5]:
np.concatenate((a,b),axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
a.ndim

2

In [25]:
b.ndim

2

In [24]:
b =np.expand_dims(b,axis=0)

In [22]:
b= np.squeeze(b)

In [26]:
b

array([[5, 6]])

In [27]:
np.concatenate((a,b),axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [29]:
np.concatenate((a,b.T),axis=1) # .T -> Transpuesta de la matriz

array([[1, 2, 5],
       [3, 4, 6]])

# Documentación de Numpy: 

- [Estadística](https://numpy.org/doc/stable/reference/routines.statistics.html)
- [Funciones Matemáticas](https://numpy.org/doc/stable/reference/routines.math.html)

