# Numpy Array

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [1]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices Los elementos se emepiezan a contar desde 0. Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

In [12]:
matriz[0,2]

3

In [16]:
matriz[:2 ,1:2]

array([[2],
       [5]])

# RETO

Crear una matriz de 3 dimensiones.
- Comprueba el indexado.

In [24]:
Matriz3D = [    
                [   [1,2,3,],   [4,5,6],    [7,8,9]     ],
                [   [10,11,12], [13,14,15], [17,18,19]  ],
                [   [20,21,22], [23,24,25], [26,27,28]  ]
            ]
Matriz3D = np.array(Matriz3D)
Matriz3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [31]:
Matriz3D[:,:1,:1]

array([[[ 1]],

       [[10]],

       [[20]]])