# Creando Arrays

In [4]:
import numpy as np

In [5]:
list(range(0,10)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,10) # (Inicio, Fin, Incremento), es la método range ⬆️ pero en Numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros((3,3)) # Nos puede sirve como un borrador de los datos que podríamos tener. 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((10,10)) # Lo mismo que el formato anterior pero en 1.

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,100,52)
# Start, End, Num.Datos nos da la distribución de los datos de acuerdo a los parámetros que se establezcan. 

array([  0.        ,   1.96078431,   3.92156863,   5.88235294,
         7.84313725,   9.80392157,  11.76470588,  13.7254902 ,
        15.68627451,  17.64705882,  19.60784314,  21.56862745,
        23.52941176,  25.49019608,  27.45098039,  29.41176471,
        31.37254902,  33.33333333,  35.29411765,  37.25490196,
        39.21568627,  41.17647059,  43.1372549 ,  45.09803922,
        47.05882353,  49.01960784,  50.98039216,  52.94117647,
        54.90196078,  56.8627451 ,  58.82352941,  60.78431373,
        62.74509804,  64.70588235,  66.66666667,  68.62745098,
        70.58823529,  72.54901961,  74.50980392,  76.47058824,
        78.43137255,  80.39215686,  82.35294118,  84.31372549,
        86.2745098 ,  88.23529412,  90.19607843,  92.15686275,
        94.11764706,  96.07843137,  98.03921569, 100.        ])

In [19]:
np.eye(4) # Genera la matriz identidad <- Algebra Lineal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(4,4,4) # ( Dimensiones ) Parámetro es el num. de datos aleatorios que va a generar

array([[[0.3525934 , 0.99489901, 0.57490531, 0.60989915],
        [0.52906633, 0.09783979, 0.57070815, 0.50854055],
        [0.11737646, 0.35318126, 0.62948606, 0.68237994],
        [0.13607491, 0.34541039, 0.49967146, 0.78252552]],

       [[0.4030481 , 0.74735188, 0.07750883, 0.32046547],
        [0.71750729, 0.72845931, 0.86160618, 0.04542291],
        [0.30152623, 0.90664081, 0.77782676, 0.66981328],
        [0.13258743, 0.72547852, 0.54977612, 0.71902874]],

       [[0.48731001, 0.43664284, 0.07941299, 0.02000752],
        [0.68424815, 0.06945256, 0.37988846, 0.92110467],
        [0.74322121, 0.17226079, 0.66859469, 0.9300214 ],
        [0.92660638, 0.2548094 , 0.50212497, 0.9289238 ]],

       [[0.50539669, 0.28021396, 0.49095342, 0.78573995],
        [0.53789082, 0.29119208, 0.14056946, 0.29789447],
        [0.41213291, 0.65498824, 0.61509367, 0.04069092],
        [0.90989029, 0.06682026, 0.87953714, 0.03411936]]])

In [39]:
np.random.randint(1,1000) #(Start, End, Dimension)  Genera un numero aleatorio entero entre el inicio y final 

11

In [43]:
np.random.randint(1,100,(10,10))

array([[41,  2, 42, 47, 59, 25, 14, 11, 25, 40],
       [90, 11, 45, 83, 29, 50, 97, 13, 59, 35],
       [10, 92, 23, 74, 66, 31, 84, 12, 21, 16],
       [20, 80, 35, 30, 80, 25, 56, 80, 66, 31],
       [87, 52, 24, 83, 90, 76, 73, 23,  9, 76],
       [13, 80, 81,  7, 73, 50,  4, 55, 31,  2],
       [65, 72,  7, 29, 83, 94, 45, 52, 24, 22],
       [73, 95, 63, 14, 63, 32, 19, 44, 19, 30],
       [ 5, 20, 94, 12, 19, 86, 87,  1, 78, 53],
       [41, 36, 27, 56, 77, 69, 98, 26,  8, 18]])